parameters:
    city.entity.class: "PM\GBundle\Entity\City"
    city.entity.manager: "PM\GBundle\EntityManager\CityManager"

    coordiante.entity.class: "PM\GBundle\Entity\Coordinate"
    coordinate.entity.manager: "PM\GBundle\EntityManager\CoordinateManager"

    game.entity.class: "PM\GBundle\Entity\Game"
    game.entity.manager: "PM\GBundle\EntityManager\GameManager"

    score.entity.class: "PM\GBundle\Entity\Score"
    score.entity.manager: "PM\GBundle\EntityManager\ScoreManager"

    task.entity.class: "PM\GBundle\Entity\Task"
    task.entity.manager: "PM\GBundle\EntityManager\TaskManager"

services:
    manager.city:
        class: %city.entity.manager%
        arguments: [%city.entity.class% @doctrine.orm.entity_manager, @security.context]

    manager.coordinate:
        class: %coordinate.entity.manager%
        arguments: [%coordiante.entity.class% @doctrine.orm.entity_manager, @security.context]

    manager.game:
        class: %game.entity.manager%
        arguments: [%game.entity.class% @doctrine.orm.entity_manager, @security.context]

    manager.score:
        class: %score.entity.manager%
        arguments: [%score.entity.class% @doctrine.orm.entity_manager, @security.context]

    manager.task:
        class: %task.entity.manager%
        arguments: [%task.entity.class% @doctrine.orm.entity_manager, @security.context]



